@startuml
'#------------------------------------------------
'#
'#  Gantt chart template
'#  References
'#  - (plantuml)[https://plantuml.com/]
'#  - (plantuml preprocessing)[https://plantuml.com/preprocessing]
'#  - (plantuml preprocessing-json)[https://plantuml.com/preprocessing-json]
'#  - (plantuml gantt-diagram)[https://plantuml.com/gantt-diagram]
'#  - (plantuml skinparam)[https://plantuml.com/skinparam]
'#  - (plantuml color)[https://plantuml.com/color]
'#
'#------------------------------------------------
'#------------------------------------------------
'# Settings
'#------------------------------------------------
'# default
!$default_setting={
    "project_starts":"2022/01/01",
    "project_ends":"2022/05/01",
    "scale":"1.2",
    "printscale":{
        "scale":"weekly",
        "zoom":1
    },
    "language":"ja"
}

'# load json
!$settings = %loadJSON("./config/gantt_chart_setting.json",$default_setting)

'#------------------------------------------------
'# Gantt data
'#------------------------------------------------
'# default
!$default_gantt={
    "root":[
        {"level3":"Failed to load json file.","p_starts_at":"2022/01/01", "p_ends_at":"2022/05/01"}
    ]
}

'# load json
!$schedule = %loadJSON("./schedule.json", $default_gantt)

'#------------------------------------------------
'# If $value is invalid, returns the $empty.
'# Otherwise, returns the marged value of $prefix, $value, and $postfix. 
'#------------------------------------------------
!function $_($prefix="",$value,$postfix="",$empty="")
    !if $value==""
        !return $empty
    !else
        !return $prefix+$value+$postfix
    !endif
!endfunction

'#------------------------------------------------
'# Show the tasks.
'#------------------------------------------------
!procedure $main($l_schedule)
    !$task_id = 0
    !foreach $item in $l_schedule
        $_("--<font color=#336688><size:13>__**[",$item.level1,"]**__--")
        $_("--<font color=#337799>",$item.level2,"--")

        !if $item.level3 != ""
            '# If starts date is the same as ends date, show task as milestone.
            !if $item.p_starts_at == $item.p_ends_at
                [**$_("",$item.p_starts_at," : ", "") $item.level3**] as [$task_id] happens at $item.p_starts_at
            !else
                [**$_("",$item.progress,"% - ", "0% - ") $item.level3**] as [$task_id] starts at $item.p_starts_at and ends at $item.p_ends_at
            !endif

            '# Show progresses.
            $_([$task_id]+" is ",$item.progress,"%  completed", [$task_id] + " is 0% completed")

            '# Coloring based on progress and date.
            !if $item.progress=="100"
                [$task_id] is colored in LightGray/Gray
            !elseif $item.progress=="0" || $item.progress==""
                !if $item.p_starts_at < $today
                    [$task_id] is colored in lightpink/Red
                !else
                    [$task_id] is colored in Lime/Green
                !endif
            !else
                !if $item.p_ends_at < $today
                    [$task_id] is colored in lightpink/Red
                !else
                    [$task_id] is colored in lightskyblue/darkblue
                !endif
            !endif
        !endif
        !$task_id = $task_id + 1
    !endfor
!end procedure

'#----------------------------------------------
'# Other setting and call the main function.
'#----------------------------------------------
$_("scale ", $settings.scale)
$_("printscale ", $settings.printscale.scale, $_(" zoom ",$settings.printscale.zoom))
$_("language ", $settings.language)
$_("project starts ", $settings.project_starts)
$_("[.] happens at ", $settings.project_ends, " and is colored in White")
hide footbox
!$today = %date("yyyy/MM/dd")
today is $today and is colored in Red
$main($schedule.root)

'#----------------------------------------------
'# Skin setting
'#----------------------------------------------
!include ./gantt_chart_skin.pu

@enduml
