@startuml
<style>
ganttDiagram {
    arrow {
        LineColor Lime
        LineThickness 0.5
    }
    timeline {
        BackgroundColor Gray
        FontColor white
    }
    separator {
        LineColor #999999
    }
}
</style>
@enduml